name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 13 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.3'
          - '3.4'
          - '4.0'
          - 'ruby' # latest stable release
        activerecord-version:
          - '8_0'
          - '8_1'
          - 'latest'
        mysql-version:
          - '8.0' # Aurora MySQL version 3, which is compatible with MySQL 8.0, reaches EOL on April 30, 2028
          - '8.4'
          - '9.7'
    services:
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test

    env:
      BUNDLE_GEMFILE: gemfiles/activerecord_${{ matrix.activerecord-version }}.gemfile

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Show activerecord version
        run: bundle info activerecord

      - name: Run tests
        run: |
          bundle exec rake
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
