name: CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
        activerecord-version:
          - '6_0'
          - '6_1'
          - '7_0'
          - '7_1'
        exclude:
          # activerecord-7 doesn't support Ruby 2.6
          - ruby-version: '2.6'
            activerecord-version: '7_0'
          - ruby-version: '2.6'
            activerecord-version: '7_1'

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test

    env:
      BUNDLE_GEMFILE: gemfiles/activerecord_${{ matrix.activerecord-version }}.gemfile

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Build and test with Rake
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rake
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
